### ISSUE TITLE
Blender 2.93.3 Exporting zero values issue

### ISSUE THREAD

**Issue by truong-bui** [qerrant/BezierBlenderToUE#1]
Hi @qerrant thank you very much for the add-on. I'm using Blender 2.93.3, and all values are zero when exported. A quick fix is to replace **%d** to **%f** for float value. Thanks again.
![image](https://user-images.githubusercontent.com/1840964/131384066-fa66a4be-99f9-4359-bbeb-d5623e9cb923.png)

Best Regards,
Truong

**Comment by qerrant** [comment]
> 
> 
> Hi @qerrant thank you very much for the add-on. I'm using Blender 2.93.3, and all values are zero when exported. A quick fix is to replace **%d** to **%f** for float value. Thanks again.
> ![image](https://user-images.githubusercontent.com/1840964/131384066-fa66a4be-99f9-4359-bbeb-d5623e9cb923.png)
> 
> Best Regards,
> Truong

Hi! Thank you for your question and answer! Sure, you correctly noticed.
